{
  "formatVersion": "1.1",
  "component": {
    "group": "com.picup.sdk",
    "module": "core",
    "version": "5.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "EnvTestVariantEnvTestApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-5.0.2.aar",
          "url": "core-5.0.2.aar",
          "size": 1676817,
          "sha512": "6d2441b8d97290065b849c829d232f9978299776922fc64b3901c774ed4ed7e51af63ff37e6666324ac7de266fcde7275b0ed89d568f9639f287d16e05eeb535",
          "sha256": "d6fbedd757bc39bae5745b2c1bc69325b186da75ee011c083ab39c85aa2a4780",
          "sha1": "ae7ed1729764c780aa1f14d792a7ebe5a3a06199",
          "md5": "a4a7ff47531287761bb7241e1526cce8"
        }
      ]
    },
    {
      "name": "EnvTestVariantEnvTestRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mixpanel.android",
          "module": "mixpanel-android",
          "version": {
            "requires": "5.8.7"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "23.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-gcm",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.castorflex.smoothprogressbar",
          "module": "library-circular",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.conscrypt",
          "module": "conscrypt-android",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-5.0.2.aar",
          "url": "core-5.0.2.aar",
          "size": 1676817,
          "sha512": "6d2441b8d97290065b849c829d232f9978299776922fc64b3901c774ed4ed7e51af63ff37e6666324ac7de266fcde7275b0ed89d568f9639f287d16e05eeb535",
          "sha256": "d6fbedd757bc39bae5745b2c1bc69325b186da75ee011c083ab39c85aa2a4780",
          "sha1": "ae7ed1729764c780aa1f14d792a7ebe5a3a06199",
          "md5": "a4a7ff47531287761bb7241e1526cce8"
        }
      ]
    }
  ]
}
