{
  "formatVersion": "1.1",
  "component": {
    "group": "com.picup.sdk",
    "module": "core",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "EnvTestVariantEnvTestApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-5.0.0.aar",
          "url": "core-5.0.0.aar",
          "size": 1676450,
          "sha512": "c3e34e4feb119d7742f259a3cd3cbeb699c391ecf85ca44290c0c5e0faa98aabaf25b61249d1eac75c433da4bba528cbb38ab1e26c91f938307f087a10a37fe5",
          "sha256": "f76a08790662dee8a9e77910cefcbe4a2da90ec8cb4d9ca5de96794bbadbdea9",
          "sha1": "fe706229f498d30fe6118c2969d9d46801966b1a",
          "md5": "f488068a367ad47f609c28b73b47b704"
        }
      ]
    },
    {
      "name": "EnvTestVariantEnvTestRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mixpanel.android",
          "module": "mixpanel-android",
          "version": {
            "requires": "5.8.7"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.splunk.mint",
          "module": "mint",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "23.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-gcm",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.castorflex.smoothprogressbar",
          "module": "library-circular",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.conscrypt",
          "module": "conscrypt-android",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-5.0.0.aar",
          "url": "core-5.0.0.aar",
          "size": 1676450,
          "sha512": "c3e34e4feb119d7742f259a3cd3cbeb699c391ecf85ca44290c0c5e0faa98aabaf25b61249d1eac75c433da4bba528cbb38ab1e26c91f938307f087a10a37fe5",
          "sha256": "f76a08790662dee8a9e77910cefcbe4a2da90ec8cb4d9ca5de96794bbadbdea9",
          "sha1": "fe706229f498d30fe6118c2969d9d46801966b1a",
          "md5": "f488068a367ad47f609c28b73b47b704"
        }
      ]
    }
  ]
}
